config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Existing routes for foods and recipes
  resources :foods
  resources :recipes do
    put 'toggle_public', on: :member
    member do
      get 'shoping_list'
    end
  end
  resources :food_recipes, only: [:new, :create, :destroy]
  root 'recipes#public'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # Attributes
  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true

  belongs_to :user
  has_many :food_recipes, dependent: :destroy
  has_many :foods, through: :food_recipes, class_name: 'Food', foreign_key: 'food_id'
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:public]

  def public
    @public_page = true
    @recipes = Recipe.includes(%i[foods food_recipes user]).where(public: true).order('created_at DESC')
    @public_recipe_data_list = []
    @recipes.each do |recipe|
      public_recipe_data = {}
      public_recipe_data[:user] = recipe.user.name
      public_recipe_data[:recipe] = recipe
      public_recipe_data[:recipe_name] = recipe.name
      public_recipe_data[:food_count] = recipe.foods.length
      public_recipe_data[:total_price] = recipe.food_recipes.reduce(0) do |total_price, food_recipe|
        total_price + (food_recipe.food.price * food_recipe.quantity)
      end
      @public_recipe_data_list << public_recipe_data
    end
  end

  def shoping_list
    @recipe = Recipe.includes(:foods, :food_recipes, :user).find(params[:id])
    @recipe_shoping_list_data = {}
    @recipe_shoping_list_data[:recipe_name] = @recipe.name
    @recipe_shoping_list_data[:food_count] = @recipe.foods.length
    p @recipe.food_recipes
    @recipe_shoping_list_data[:foods_data] = @recipe.food_recipes.map do |food_recipe|
      {
        name: food_recipe.food.name,
        quantity: food_recipe.quantity,
        price: food_recipe.food.price * food_recipe.quantity
      }
    end
    @recipe_shoping_list_data[:total_price] = @recipe.food_recipes.reduce(0) do |total_price, food_recipe|
      total_price + (food_recipe.food.price * food_recipe.quantity)
    end
  end

  def index
    @recipes = Recipe.where(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @recipe = Recipe.includes(:food_recipes).find(params[:id])
    @food_recipes = @recipe.food_recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params.merge(user_id: current_user.id))
    if @recipe.save
      redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if params[:public].present?
        if @recipe.update(public: params[:public])
          format.html { redirect_to recipe_url(@recipe), notice: 'Public attribute was successfully updated.' }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      elsif @recipe.update(recipe_params)
        # Handle other attributes here
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe attributes were successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: params[:recipe][:public])
    respond_to do |format|
      format.json { render json: { success: true } }
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def add_ingredient
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food_params = recipe_ingredient_params

    # Create a new RecipeFood record to associate the selected food with the recipe
    @recipe_food = RecipeFood.new(recipe_food_params)

    if @recipe_food.save
      flash[:success] = 'Ingredient added successfully'
      redirect_to @recipe
    else
      render 'add_ingredient'
    end
  end

  def new_ingredient
    @recipe = set_recipe
    @food = Food.new
  end

  def destroy_ingredient
    @food = Food.find(params[:food_id])
    @recipe.food.delete(@food)
  end

  private

  def recipe_ingredient_params
    params.require(:recipe).permit(food_recipes_attributes: %i[quantity food_id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id, :quantity)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: 'forms') do |form| %>
      <% if recipe.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% recipe.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :preparation_time, style: "display: block" %>
        <%= form.text_field :preparation_time %>
      </div>

      <div>
        <%= form.label :cooking_time, style: "display: block" %>
        <%= form.text_field :cooking_time %>
      </div>

      <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description, class: 'desc-block', rows: 6, cols: 40 %>
      </div>

      <div>
        <%= form.submit 'Submit', class: 'submit-btn' %>
      </div>
<% end %>

app/views/recipes/_public_recipe_card.html.erb
<div class="gen-form-container cont" >
  <div class="recipe-card">
    <div class="recipe-subclass">
      <div class="name-del">
      <h2><%= public_recipe_data[:recipe].name %></h2><br>
      <p class="capi">By: <strong><%= public_recipe_data[:user] %></strong></p>
    </div>
    <div class="desc">
      <p>Total food: <%= public_recipe_data[:food_count] %></p>
      <p>Total price: <%= public_recipe_data[:total_price] %></p>
    </div>
    </div>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>
  <% @recipe.food.each do |food| %>
    <%= food.name %> <%= button_to 'remove', destroy_ingredient_recipe_path(id: @recipe.id, food_id: food.id), method: :post %>
    </br>
  <% end %>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="cont">
  <div class="row justify-content-center">
  <div class="col-lg-4 col-10 d-flex ">
    <% if @public_page %>
      <h1 class="text-success">Public Recipes</h1>
    <% else %> 
      <h1 class="text-success">My Recipes</h1>
    <% end %>
  </div>
  
</div>


<div id="recipes" class="">
  <% if @recipes.present? %>
  <% @recipes.each do |recipe| %>
  <div class="">
       <%= render partial: 'shared/recipe_card', locals: { recipe: recipe } %>
  </div>
  <% end %>
  <% else %>
   <h4 class="text-center p-5">you have no recipes</h4>
  <% end %>
       <%= link_to "Add new recipe", new_recipe_path, class: '' %>
</div>
</div>

app/views/recipes/new.html.erb
<div class="gen-form-cont">
   <div class="form-container">
    <h1>New recipe</h1>

    <%= render "form", recipe: @recipe %>

    <br>

    <div>
      <%= link_to "Back to recipes", recipes_path %>
    </div>
  </div>
</div>

app/views/recipes/new_ingredient.html.erb
<!-- views/recipes/new_ingredient.html.erb -->

<div class="gen-form-container cont">
  <h1 class="mg-b"><%= @recipe.name %></h1>
  <!-- Add ingredient form -->
  <%= form_for @recipe, url: add_ingredient_recipe_path(@recipe), local: true, method: :post do |form| %>
  <div class="form-group">
    <%= form.label :food_id, 'Food' %>
    <%= form.collection_select :food_recipes_attributes, :food_id, :id, :name, prompt: 'Select a food', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :food_recipes_attributes, :quantity, class: 'form-control' %>
  </div>

  <div class="form-actions">
    <%= form.submit 'Add Ingredient', class: 'btn btn-primary' %>
  </div>
<% end %>

</div>

app/views/recipes/public.html.erb
<div class="cont">
<p style="color: green"><%= notice %></p>

<h1>Public Recipes Updated</h1>

<div id="recipes">
  <% @public_recipe_data_list.each do |public_recipe_data| %>
    <%= render partial: 'public_recipe_card', locals: { public_recipe_data: public_recipe_data }   %>
    <p>
      <%= link_to "Show this recipe", public_recipe_data[:recipe] %>
    </p>
  <% end %>
</div>
<br>

<div class="contain-btn">
    <% if user_signed_in? %>
    <%= link_to "New Recipe", new_recipe_path, class: 'submit-btn' %>
    <%else%>
    <%= link_to "New Recipe", new_user_session_path, class: 'submit-btn' %>
    <%end%> <br>

    <% unless user_signed_in? %>
        <%= button_to "Sign in", new_user_session_path, method: :get, class: "danger-btn" %>
    <%end%>
</div>
</div>

app/views/recipes/public_recipes.html.erb
<div class='container vertical_flex '>
<p style="color: green"><%= notice %></p>

<h1>Public Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<% if user_signed_in? %>
<%= link_to "New Recipe", new_recipe_path %>
<%else%>
<%= link_to "New Recipe", new_user_session_path %>
<%end%>
</div>

app/views/recipes/shoping_list.html.erb
<div class='container vertical_flex '>
<p style="color: green"><%= notice %></p>

<h1>Shoping List</h1>

<div id="recipes">
   <div>
    <p>
        <strong>Amount of food items to buy:</strong>
        <%= @recipe_shoping_list_data[:food_count] %>
    </p>
    <p>
        <strong>Total value of food needed:</strong>
        <%= @recipe_shoping_list_data[:total_price] %>
    </p>
   </div>
   <table class="grid-table" id="foods">
        <thead>
            <tr>
                <th><strong>Food</strong></th>
                <th><strong>Quantity</strong></th>
                <th> <strong>Price</strong></th>
            </tr>
        </thead>
        <tbody>
            <% @recipe_shoping_list_data[:foods_data].each do |food_data| %>
                <tr>
                    <td>
                    <%= link_to food_path(food_data), class: 'link' do %>
                        <%= food_data[:name] %>
                        <%end%>
                    </td>

                    <td>
                        
                        <%= food_data[:quantity] %>
                    </td>

                    <td>
                    
                        <%= food_data[:price] %>
                    </td>

                </tr>

            <% end %>
  </tbody>
  </table>
</div>
<br>

<% if user_signed_in? %>
<%= link_to "New Recipe", new_recipe_path, class: 'submit-btn' %>
<%else%>
<%= link_to "New Recipe", new_user_session_path, class: 'submit-btn' %>
<%end%> <br>

<% unless user_signed_in? %>
    <%= button_to "Sign in", new_user_session_path, method: :get, class: "danger-btn" %>
<%end%>
</div>

app/views/recipes/show.html.erb
<div class="gen-form-container cont">
  <h1 class="mg-b"><%= @recipe.name %></h1>
  <div class="show-recipe mg-b">
    <div class="details-food">
      <p class="details-p">
        <strong>Preparation time:</strong>
        <span><%= @recipe.preparation_time %> <% if @recipe.preparation_time > 1 %>
          hours
          <% else %>
          hour
          <% end %></span>
      </p>
      <p class="details-p">
        <strong>Cooking time:</strong>
        <span><%= @recipe.cooking_time %> <% if @recipe.cooking_time > 1 %>
          hours
          <% else %>
          hour
          <% end %></span>
      </p>
      <p class="details-p">
        <strong>Description:</strong>
        <span><%= @recipe.description %></span>
      </p>
    </div>
    <div class="toggle-btn">
    <% if current_user.present? && current_user.id == @recipe.user.id %>
    <%= form_with model: @recipe, local: true, html: { id: 'recipe-form' } do |form| %>
      <span>Public</span>
      <label for="public-toggle" class="switch">
        <%= form.check_box :public, { id: "public-toggle", onchange: "this.form.submit()" } %>
        <div class="slider"></div>
      </label>
    <% end %>
    <% end %>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="action-btns">
      <%= link_to 'Generate shopping list', shoping_list_recipe_path(@recipe) ,class: 'view-btn' %>
      <%= link_to 'Add Ingredients', new_food_recipe_path(recipe_id: @recipe.id), class: 'view-btn' %>
    </div>
  <% end %>
  <table class="food-table">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tbody>
        <% if @food_recipes.present? %>
    <% @food_recipes.each do |food_recipe| %>
      <tr>
        <td><%= food_recipe.food.name %></td>
        <td>
          <%= food_recipe.quantity %>
        </td>
        <td><%= food_recipe.value %></td> 
        <td>
          <%= link_to 'Delete', food_recipe_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'danger-btn' %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="4">No ingredients added yet</td>
    </tr>
  <% end %>
      </tbody>
    </tbody>
  </table>
</div>