config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Existing routes for foods and recipes
  resources :foods
  resources :recipes do
    put 'toggle_public', on: :member
    member do
      get 'shoping_list'
    end
  end
  resources :food_recipes, only: [:new, :create, :destroy]
  root 'recipes#public'
end

app/models/food.rb
class Food < ApplicationRecord
  # Attributes
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  belongs_to :user
  has_many :food_recipes
  has_many :recipes, through: :food_recipes, class_name: 'Recipe', foreign_key: 'recipe_id'
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    authorize! :create, @food

    @food.user = current_user
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    authorize! :destroy, @food
    @food.destroy
    redirect_to foods_url, notice: 'Food was successfully destroyed.'
  rescue ActiveRecord::InvalidForeignKey
    redirect_to foods_url, alert: 'This food item cannot be deleted because it is associated with other records.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<tr>

  <td>
  <%= link_to food_path(food), class: 'link' do %>
    <%= food.name %>
    <%end%>
  </td>

  <td>
    
    <%= food.measurement_unit %>
  </td>

  <td>
   
    <%= food.price %>
  </td>

  <td>
  <% if can? :destroy, food %>
  <%= button_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: 'danger-btn' %>
<% end %>

  </td>

</tr>

app/views/foods/_form.html.erb
<div class='container '>
<%= form_with(model: food, class: 'forms') do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= 'field'>
   
    <%= form.text_field :name, placeholder: 'name' %>
  </div>

  <div class= 'field'>
    
    <%= form.text_field :measurement_unit, placeholder: 'Measurement_unit' %>
  </div>

  <div class= 'field'>
   
    <%= form.text_field :price, placeholder: 'price' %>
  </div>

 
  <div>
    <%= form.submit 'Add Food', class: 'view-btn' %>
  </div>
<% end %>
</div>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>
<div class= 'container'>
<div class='horizontal_flex_end '>
<div>
<% if user_signed_in? %>
<%= link_to "New food", new_food_path, class: 'submit-btn' %>
<%else%>
<%= link_to "New food", new_user_session_path, class: 'submit-btn' %>
<%end%>
</div>
</div>
<table class="grid-table" id="foods">
        <thead>
            <tr>
                <th><strong>Food</strong></th>
                <th><strong>Measurement unit</strong></th>
                <th> <strong>Price</strong></th>
                <th> <strong>Action</strong></th>
            </tr>
        </thead>
        <tbody>

  <% @foods.each do |food| %>
    
    <%= render food %>
   
     
  
  <% end %>
  </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="gen-form-cont">
   <div class="form-container">
    <h1>New food</h1><br>

    <%= render "form", food: @food %>

    <br>

    <div>
      <%= link_to "Back to foods", foods_path %>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<div class='container vertical_flex '>
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>
</div>